services:
  - type: web
    name: diary-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false